### ISSUE TITLE
Version management of project in the src folder

### ISSUE THREAD

**Issue by cruisemaniac** [nicbet/docker-phoenix#11]
I'm at this point where I'm having trouble organising the content inside the src folder.

There's 2 options:

1. Treat each phoenix project with `docker-phoenix` as part of the skeleton codebase
2. Treat `docker-phoenix` as a separate project and have `./src` symlinked via some means into `./docker-phoenix/`

Both these options are viable and are at play in similar offerings like laradock.

Let me know what you think and I'll PR accordingly.

**Comment by gofighting123** [comment]
hi, i got a problem when following the readme, but i can't finish the build step. here are the result as bellow:
$ ./mix phx.new . --app hello
Pulling db (postgres:10)...
10: Pulling from library/postgres
a5a6f2f73cd8: Already exists
e50fbea8af5a: Already exists
73b4855ad326: Already exists
39616673f22b: Already exists
94e1b79f69ee: Downloading [==========>                                        ]  1.359MB/6.183MB

i can't finish this downloading. 
so, what can i do , switch to another mirror ?

**Comment by nicbet** [comment]
@gofighting123 I've moved your question to a new issue #13
