### ISSUE TITLE
Build step doesn't finish on downloading docker layer

### ISSUE THREAD

**Issue by nicbet** [nicbet/docker-phoenix#13]
hi, i got a problem when following the readme, but i can't finish the build step. here are the result as bellow:

$ ./mix phx.new . --app hello
Pulling db (postgres:10)...
10: Pulling from library/postgres
a5a6f2f73cd8: Already exists
e50fbea8af5a: Already exists
73b4855ad326: Already exists
39616673f22b: Already exists
94e1b79f69ee: Downloading [==========>                                        ]  1.359MB/6.183MB

i can't finish this downloading. 
so, what can i do , switch to another mirror ?

is there anything wrong? i am in win10 and i use docker-terminal mode to excute the script.

_Originally posted by @gofighting123 in https://github.com/nicbet/docker-phoenix/issues/11#issuecomment-447755784_

**Comment by gofighting123** [comment]
i just fixed this problem by switching to my own wifi mobile network. it works :)
still working on the next problem: ** (Mix) The task "ecto.create" could not be found A.A....

**Comment by nicbet** [comment]
@gofighting123 Feel free to open a new issue with the full error message.
