### ISSUE TITLE
Many of the tagged commits are showing up as unverified.

### ISSUE THREAD

**Issue by restlessronin** [nicbet/docker-phoenix#26]
@nicbet First of all, thanks for creating this project. I wish I had found it when I first started dockerizing phoenix, it would have saved me a ton of learning from scratch. But I'm happy I did find it eventually.

Just a small issue. In https://github.com/nicbet/docker-phoenix/tags around half the tags are being marked as "unverified". it's probably not a huge deal, but the neurotic in me noticed, and I thought I'd point it out.

**Comment by nicbet** [comment]
Hi @restlessronin, the commits from yesterday were made on a new laptop that wasn't set up with my GPG key yet. Amending these is possible, but I'd re required to force push a new history - not going to do that. Will sign going forward.
