### ISSUE TITLE
segfault on mix phx.new

### ISSUE THREAD

**Issue by surajsharma** [nicbet/docker-phoenix#35]
`mix phx.new . hello_world` gives the following error:

qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault

**Comment by nicbet** [comment]
@surajsharma that tends to happen when you use an emulation layer for Docker on an ARM architecture. Are you by any chance developing on an M1 or M2 Apple device and running the x86 container? If so, please rebuild the container for your native architecture and try again.

**Comment by BIRSAx2** [comment]
Still getting this error using Docker on WSL2
